CREATE TABLE impiegato (
    MATR INT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DATA_ASS DATE NOT NULL,
    SALARIO INT NOT NULL,
    MATR_MGR INT,
    FOREIGN KEY (MATR_MGR) REFERENCES impiegato(MATR),
    ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE progetto (
    NUM_PROG INT PRIMARY KEY,
    TITOLO VARCHAR(50) NOT NULL,
    TIPO VARCHAR(50) NOT NULL
)

CREATE TABLE assegnamento (
    MATR INT,
    NUM_PROG INT,
    PERC INT,
    PRIMARY KEY (MATR, NUM_PROG),
    FOREIGN KEY (MATR) REFERENCES impiegato(MATR),
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (NUM_PROG) REFERENCES progetto(NUM_PROG),
    ON DELETE CASCADE ON UPDATE CASCADE
)